volumes:
  pgdata:
  rabbitmq_data:


services:
  app:
    build: .
    container_name: stock_market_tochka
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: $SECRET_KEY
    depends_on:
      - db
    command: ["bash", "./start_api.sh"]

  db:
    image: postgres:14
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: $POSTGRESQL_HOST
      POSTGRES_PORT: $POSTGRESQL_PORT
      POSTGRES_USER: $POSTGRESQL_USER
      POSTGRES_PASSWORD: $POSTGRESQL_PASS
      POSTGRES_DB: $POSTGRESQL_NAME
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
