"""initial

Revision ID: ba60f0b4fb59
Revises:
Create Date: 2025-03-23 17:54:58.723077

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import FetchedValue

# revision identifiers, used by Alembic.
revision: str = "ba60f0b4fb59"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instrument",
        sa.Column(
            "id", sa.Uuid(), server_default=FetchedValue(), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id", sa.Uuid(), server_default=FetchedValue(), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), server_default="USER", nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "balances",
        sa.Column(
            "id", sa.Uuid(), server_default=FetchedValue(), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_balances_ticker"), "balances", ["ticker"], unique=False
    )
    op.create_index(
        op.f("ix_balances_user_id"), "balances", ["user_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column(
            "id", sa.Uuid(), server_default=FetchedValue(), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "executed",
                "partially_executed",
                "cancelled",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("buy", "sell", name="orderdirection"),
            nullable=False,
        ),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("filled", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker"),
    )
    op.create_index(
        op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_balances_user_id"), table_name="balances")
    op.drop_index(op.f("ix_balances_ticker"), table_name="balances")
    op.drop_table("balances")
    op.drop_table("users")
    op.drop_table("instrument")
    sa.Enum(name="orderstatus").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="orderdirection").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
